/* Fetch Predictions */
export const FETCH_PEOPLE_TRAFFIC_PREDICTIONS_START = "FETCH_PEOPLE_TRAFFIC_PREDICTIONS_START";
export const FETCH_PEOPLE_TRAFFIC_PREDICTIONS_SUCCESS = "FETCH_PEOPLE_TRAFFIC_PREDICTIONS_SUCCESS";
export const FETCH_PEOPLE_TRAFFIC_PREDICTIONS_ERROR = "FETCH_PEOPLE_TRAFFIC_PREDICTIONS_ERROR";

/* Fetch Tweets */
export const FETCH_TWEETS_START = "FETCH_TWEETS START";
export const FETCH_TWEETS_SUCCESS = "FETCH_TWEETS_SUCCESS";
export const FETCH_TWEETS_ERROR = "FETCH_TWEETS_ERROR";